# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0
# Adapted for Orb project, modifications licensed under MPL v. 2.0:
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

apiVersion: v2
name: orb
description: Orb Observability Platform
icon: https://avatars1.githubusercontent.com/u/13207490
type: application
version: 1.0.8
appVersion: "0.9.0"
home: https://getorb.io
sources:
  - https://hub.docker.com/u/ns1labs/
maintainers:
  - name: ns1labs
    email: labs@ns1.com

dependencies:
  - name: jaeger-operator
    version: "2.23.0"
    repository: "@jaegertracing"
  - name: nats
    version: "6.4.2"
    repository: "@bitnami"
  - name: postgresql
    version: "10.9.1"
    repository: "@bitnami"
    alias: postgresql-fleet
  - name: postgresql
    version: "10.9.1"
    repository: "@bitnami"
    alias: postgresql-policies
  - name: postgresql
    version: "10.9.1"
    repository: "@bitnami"
    alias: postgresql-sinks
  - name: postgresql
    version: "10.9.1"
    repository: "@bitnami"
    alias: postgresql-things
  - name: postgresql
    version: "10.9.1"
    repository: "@bitnami"
    alias: postgresql-users
  - name: postgresql
    version: "10.9.1"
    repository: "@bitnami"
    alias: postgresql-auth
  - name: redis
    version: "14.8.8"
    repository: "@bitnami"
    alias: redis-streams
  - name: redis
    version: "14.8.8"
    repository: "@bitnami"
    alias: redis-auth
  - name: redis
    version: "14.8.8"
    repository: "@bitnami"
    alias: redis-mqtt

